### PR TITLE
remove b

### PR DESCRIPTION
**Pull request by delfick**

### CODE REVIEW

**Review by delfick — COMMENTED** [review]
asdf

**Comment by kcollasarundell** [comment]
No i think you should add C
and nto remove b at all

**Review by kcollasarundell — COMMENTED** [review]
Fail

**Comment by kcollasarundell** [comment]
1 2 3 4 5 6 7 8 9 10

11 

12

**Comment by delfick** [comment]
test

**Review by kcollasarundell — DISMISSED** [review]
1 2 3 4 5 6 7 8 9 10

11

12 13 14

**Review by kcollasarundell — DISMISSED** [review]
test socks

**Review by kcollasarundell — DISMISSED** [review]
No

**Review by kcollasarundell — APPROVED** [review]

**Pull request merged**
